![Imgur](https://i.imgur.com/5pXzCIu.png)

# Data Science va Sun'iy Intellekt Praktikum

## 3-MODUL. MA’LUMOTLARGA ISHLOV BERISH

### 3.2 Ma'lumotlarni tozalash va tayyorlash

## Ma'lumotlarni o'zgartirish

In [ ]:
import pandas as pd

### Takrorlangan qatorlarni o'chirish.
Turli sabablarga ko'ra jadvalimizda ba'zi qatorlar takrorlanishi mumkin, bunday qatorlarni o'chirib tashlash tavsiya qilinadi.

In [ ]:
df = pd.read_csv('https://raw.githubusercontent.com/anvarnarz/praktikum_datasets/main/world_population_duplicates.csv')
df.head()

   rank  country     density   densityMi    pop2021   area
0     1    Macau  21946.4667  56841.3487    658.394     30
1     2   Monaco  19755.5000  51166.7450     39.511      2
2    28  Burundi    440.3044   1140.3884  12255.433  27834
3     1    Macau  21946.4667  56841.3487    658.394     30
4     2   Monaco  19755.5000  51166.7450     39.511      2

Avval qator takroriy ekanini tekshirish uchun `.duplicated()` metodiga muorjaat qilamiz. Bunday takroriy qatorlar `True`, takrorlanmagan qatorlar `False` qiymatinin qaytaradi.

In [ ]:
df.duplicated()

0      False
1      False
2      False
3       True
4       True
       ...
242    False
243    False
244    False
245    False
246    False
Length: 247, dtype: bool

`sum()` funksiyasi yordamida jami takrorlangan qatorlar sonini ko'rishimiz mumkin:

In [ ]:
sum(df.duplicated())

15

Jami qatorlar soni:

In [ ]:
df.shape

(247, 6)

Takrorlangan qatorlarni tashlab yuboramiz:

In [ ]:
df.drop_duplicates()

     rank           country     density   densityMi    pop2021     area
0       1             Macau  21946.4667  56841.3487    658.394       30
1       2            Monaco  19755.5000  51166.7450     39.511        2
2      28           Burundi    440.3044   1140.3884  12255.433    27834
5       3         Singapore   8305.1915  21510.4461   5896.686      710
6       4         Hong Kong   6841.3134  17719.0017   7552.810     1104
..    ...               ...         ...         ...        ...      ...
242   228           Namibia      3.1338      8.1166   2587.344   825615
243   229    Western Sahara      2.3003      5.9577    611.875   266000
244   230          Mongolia      2.1286      5.5129   3329.289  1564110
245   231  Falkland Islands      0.2902      0.7517      3.533    12173
246   232         Greenland      0.0263      0.0680     56.877  2166086

[232 rows x 6 columns]

Takroriy qiymatlarni butun jadval bo'yicha emas, ma'lum bir ustun bo'yicha ham topib o'chirish mumkin. Misol uchun, yuqoridagi jadvlada davlat nomi (`country`) yoki reytingi (`rank`) bo'yicha qidirish kifoya:

In [ ]:
df.drop_duplicates(['country'])

     rank           country     density   densityMi    pop2021     area
0       1             Macau  21946.4667  56841.3487    658.394       30
1       2            Monaco  19755.5000  51166.7450     39.511        2
2      28           Burundi    440.3044   1140.3884  12255.433    27834
5       3         Singapore   8305.1915  21510.4461   5896.686      710
6       4         Hong Kong   6841.3134  17719.0017   7552.810     1104
..    ...               ...         ...         ...        ...      ...
242   228           Namibia      3.1338      8.1166   2587.344   825615
243   229    Western Sahara      2.3003      5.9577    611.875   266000
244   230          Mongolia      2.1286      5.5129   3329.289  1564110
245   231  Falkland Islands      0.2902      0.7517      3.533    12173
246   232         Greenland      0.0263      0.0680     56.877  2166086

[232 rows x 6 columns]

In [ ]:
df.drop_duplicates(['country','rank'])

     rank           country     density   densityMi    pop2021     area
0       1             Macau  21946.4667  56841.3487    658.394       30
1       2            Monaco  19755.5000  51166.7450     39.511        2
2      28           Burundi    440.3044   1140.3884  12255.433    27834
5       3         Singapore   8305.1915  21510.4461   5896.686      710
6       4         Hong Kong   6841.3134  17719.0017   7552.810     1104
..    ...               ...         ...         ...        ...      ...
242   228           Namibia      3.1338      8.1166   2587.344   825615
243   229    Western Sahara      2.3003      5.9577    611.875   266000
244   230          Mongolia      2.1286      5.5129   3329.289  1564110
245   231  Falkland Islands      0.2902      0.7517      3.533    12173
246   232         Greenland      0.0263      0.0680     56.877  2166086

[232 rows x 6 columns]

**Yuqoridagi o'zgarishlarni saqlab qolish uchun har doimgidek inplace=True parametridan foydalanishingiz mumkin.**

### `.map()` metodi yordamida qiymatlarni almashtirish
Ushbu metod yordamida biz qatorlardagi qiymatlarni ma'lumo qoida bo'yicha o'zgartirishimiz mumkin.

Quyidagi jadvalni olaylik:

In [ ]:
df = pd.read_csv("https://github.com/anvarnarz/praktikum_datasets/raw/main/automobile_data_nan.csv", index_col=0)
df.head()

,company,body-style,wheel-base,length,engine-type,num-of-cylinders,horsepower,average-mileage,price
index,,,,,,,,,
0,alfa-romero,convertible,88.6,168.8,dohc,four,NaN,21.0,13495.0
1,alfa-romero,convertible,NaN,168.8,dohc,four,111.0,21.0,16500.0
2,alfa-romero,hatchback,94.5,171.2,ohcv,six,154.0,NaN,16500.0
3,audi,sedan,99.8,176.6,ohc,four,102.0,24.0,13950.0
4,audi,sedan,99.4,176.6,ohc,five,NaN,NaN,17450.0

`num-of-cylinders` ustunida qiymatlar son emas harf bilan yozilga. Keling shu qiymatlarni songa o'zgartiramiz.

Avvalo bu ustundagi barcha mavjud qiymatlarni ko'raylik:

In [ ]:
df['num-of-cylinders'].unique()

array(['four', 'six', 'five', 'three', 'twelve', 'two', 'eight'],
      dtype=object)

Keling endi yuqoridagi qiymatlar uchun dictionary obyekti yaratamiz:

In [ ]:
dict = {'two':2, 'three':3, 'four':4, 'five':5, 'six':6, 'eight':8, 'twelve':12}

`.map()` yordamida yuqoridagi qiymatlarni `df` ga yangi `cylinders` deb nomlangan ustun ko'rinishida qo'shamiz:

In [ ]:
df['cylinders'] = df['num-of-cylinders'].map(dict)

In [ ]:
df.head()

,company,body-style,wheel-base,length,engine-type,num-of-cylinders,horsepower,average-mileage,price,cylinders
index,,,,,,,,,,
0,alfa-romero,convertible,88.6,168.8,dohc,four,NaN,21.0,13495.0,4
1,alfa-romero,convertible,NaN,168.8,dohc,four,111.0,21.0,16500.0,4
2,alfa-romero,hatchback,94.5,171.2,ohcv,six,154.0,NaN,16500.0,6
3,audi,sedan,99.8,176.6,ohc,four,102.0,24.0,13950.0,4
4,audi,sedan,99.4,176.6,ohc,five,NaN,NaN,17450.0,5

Oxirgi ustunga ahamiyat bering. Keling avvalgi va yangi ustunlarni yonma-yon chiqaramiz:

In [ ]:
df[['num-of-cylinders','cylinders']]

      num-of-cylinders  cylinders
index
0                 four          4
1                 four          4
2                  six          6
3                 four          4
4                 five          5
...                ...        ...
81                four          4
82                four          4
86                four          4
87                four          4
88                four          4

[61 rows x 2 columns]

`.map()` yordamida ustun qiymatlariga boshqa funksiyalarni ham qo'llash mumkin. Misol uchun, keling mashina narxlarini so'mdagi qiymatini topamiz:

In [ ]:
kurs=10720 # 1$=10720 so'm
df['price'].map(lambda x: x*kurs)

index
0     144666400.0
1     176880000.0
2     176880000.0
3     149544000.0
4     187064000.0
         ...
81     85492000.0
82     85706400.0
86    107146400.0
87    138716800.0
88    143808800.0
Name: price, Length: 61, dtype: float64

Istasak, bu qiymatlarni `df` ga ham qo'shish mumkin:

In [ ]:
df['price_uzs'] = df['price'].map(lambda x: x*kurs)
df.head()

,company,body-style,wheel-base,length,engine-type,num-of-cylinders,horsepower,average-mileage,price,cylinders,price_uzs
index,,,,,,,,,,,
0,alfa-romero,convertible,88.6,168.8,dohc,four,NaN,21.0,13495.0,4,144666400.0
1,alfa-romero,convertible,NaN,168.8,dohc,four,111.0,21.0,16500.0,4,176880000.0
2,alfa-romero,hatchback,94.5,171.2,ohcv,six,154.0,NaN,16500.0,6,176880000.0
3,audi,sedan,99.8,176.6,ohc,four,102.0,24.0,13950.0,4,149544000.0
4,audi,sedan,99.4,176.6,ohc,five,NaN,NaN,17450.0,5,187064000.0

### `.replace()` Qiymatlarni almashtirish.

Qiymatlarni almashtirishning yana bir usuli bu .replace() metodi.

In [ ]:
df.head()

,company,body-style,wheel-base,length,engine-type,num-of-cylinders,horsepower,average-mileage,price,cylinders,price_uzs
index,,,,,,,,,,,
0,alfa-romero,convertible,88.6,168.8,dohc,four,NaN,21.0,13495.0,4,144666400.0
1,alfa-romero,convertible,NaN,168.8,dohc,four,111.0,21.0,16500.0,4,176880000.0
2,alfa-romero,hatchback,94.5,171.2,ohcv,six,154.0,NaN,16500.0,6,176880000.0
3,audi,sedan,99.8,176.6,ohc,four,102.0,24.0,13950.0,4,149544000.0
4,audi,sedan,99.4,176.6,ohc,five,NaN,NaN,17450.0,5,187064000.0

In [ ]:
df.replace('four',4)

,company,body-style,wheel-base,length,engine-type,num-of-cylinders,horsepower,average-mileage,price,cylinders,price_uzs
index,,,,,,,,,,,
0,alfa-romero,convertible,88.6,168.8,dohc,4,NaN,21.0,13495.0,4,144666400.0
1,alfa-romero,convertible,NaN,168.8,dohc,4,111.0,21.0,16500.0,4,176880000.0
2,alfa-romero,hatchback,94.5,171.2,ohcv,six,154.0,NaN,16500.0,6,176880000.0
3,audi,sedan,99.8,176.6,ohc,4,102.0,24.0,13950.0,4,149544000.0
4,audi,sedan,99.4,176.6,ohc,five,NaN,NaN,17450.0,5,187064000.0
...,...,...,...,...,...,...,...,...,...,...,...
81,volkswagen,sedan,97.3,171.7,ohc,4,85.0,27.0,7975.0,4,85492000.0
82,volkswagen,sedan,NaN,171.7,NaN,4,52.0,37.0,7995.0,4,85706400.0
86,volkswagen,sedan,97.3,NaN,ohc,4,100.0,NaN,9995.0,4,107146400.0
87,volvo,sedan,104.3,188.8,NaN,4,114.0,23.0,12940.0,4,138716800.0
88,volvo,wagon,104.3,188.8,ohc,4,NaN,23.0,13415.0,4,143808800.0

In [ ]:
df.replace(['four','six'],[4,6])

,company,body-style,wheel-base,length,engine-type,num-of-cylinders,horsepower,average-mileage,price,cylinders,price_uzs
index,,,,,,,,,,,
0,alfa-romero,convertible,88.6,168.8,dohc,4,NaN,21.0,13495.0,4,144666400.0
1,alfa-romero,convertible,NaN,168.8,dohc,4,111.0,21.0,16500.0,4,176880000.0
2,alfa-romero,hatchback,94.5,171.2,ohcv,6,154.0,NaN,16500.0,6,176880000.0
3,audi,sedan,99.8,176.6,ohc,4,102.0,24.0,13950.0,4,149544000.0
4,audi,sedan,99.4,176.6,ohc,five,NaN,NaN,17450.0,5,187064000.0
...,...,...,...,...,...,...,...,...,...,...,...
81,volkswagen,sedan,97.3,171.7,ohc,4,85.0,27.0,7975.0,4,85492000.0
82,volkswagen,sedan,NaN,171.7,NaN,4,52.0,37.0,7995.0,4,85706400.0
86,volkswagen,sedan,97.3,NaN,ohc,4,100.0,NaN,9995.0,4,107146400.0
87,volvo,sedan,104.3,188.8,NaN,4,114.0,23.0,12940.0,4,138716800.0
88,volvo,wagon,104.3,188.8,ohc,4,NaN,23.0,13415.0,4,143808800.0

In [ ]:
df.replace({'four':4, 'six':6})

,company,body-style,wheel-base,length,engine-type,num-of-cylinders,horsepower,average-mileage,price,cylinders,price_uzs
index,,,,,,,,,,,
0,alfa-romero,convertible,88.6,168.8,dohc,4,NaN,21.0,13495.0,4,144666400.0
1,alfa-romero,convertible,NaN,168.8,dohc,4,111.0,21.0,16500.0,4,176880000.0
2,alfa-romero,hatchback,94.5,171.2,ohcv,6,154.0,NaN,16500.0,6,176880000.0
3,audi,sedan,99.8,176.6,ohc,4,102.0,24.0,13950.0,4,149544000.0
4,audi,sedan,99.4,176.6,ohc,five,NaN,NaN,17450.0,5,187064000.0
...,...,...,...,...,...,...,...,...,...,...,...
81,volkswagen,sedan,97.3,171.7,ohc,4,85.0,27.0,7975.0,4,85492000.0
82,volkswagen,sedan,NaN,171.7,NaN,4,52.0,37.0,7995.0,4,85706400.0
86,volkswagen,sedan,97.3,NaN,ohc,4,100.0,NaN,9995.0,4,107146400.0
87,volvo,sedan,104.3,188.8,NaN,4,114.0,23.0,12940.0,4,138716800.0
88,volvo,wagon,104.3,188.8,ohc,4,NaN,23.0,13415.0,4,143808800.0

### Indeks va Ustun qiymatlarini o'zgartirish

In [ ]:
df2 = pd.read_csv('https://raw.githubusercontent.com/anvarnarz/praktikum_datasets/main/world_population_duplicates.csv', index_col='country')

In [ ]:
df2.head()

         rank     density   densityMi    pop2021   area
country
Macau       1  21946.4667  56841.3487    658.394     30
Monaco      2  19755.5000  51166.7450     39.511      2
Burundi    28    440.3044   1140.3884  12255.433  27834
Macau       1  21946.4667  56841.3487    658.394     30
Monaco      2  19755.5000  51166.7450     39.511      2

`.rename()` metodi yordamida indeks yoki ustunlar nomiga ham o'zgartirish kiritishmiz mumkin.

Quyidagi misolda indeks va ustun nomlarini katta harflar bilan yozamiz:

In [ ]:
df2.rename(index=str.upper, columns=str.upper) # Har doimngidek o'zgarishlarni saqlab qolish uchun inplace=True qilishingiz mumkin

                  RANK     DENSITY   DENSITYMI    POP2021     AREA
country
MACAU                1  21946.4667  56841.3487    658.394       30
MONACO               2  19755.5000  51166.7450     39.511        2
BURUNDI             28    440.3044   1140.3884  12255.433    27834
MACAU                1  21946.4667  56841.3487    658.394       30
MONACO               2  19755.5000  51166.7450     39.511        2
...                ...         ...         ...        ...      ...
NAMIBIA            228      3.1338      8.1166   2587.344   825615
WESTERN SAHARA     229      2.3003      5.9577    611.875   266000
MONGOLIA           230      2.1286      5.5129   3329.289  1564110
FALKLAND ISLANDS   231      0.2902      0.7517      3.533    12173
GREENLAND          232      0.0263      0.0680     56.877  2166086

[247 rows x 5 columns]

Bu metod yordamida ustun yoki indeks nomini ham o'zgartirishimiz mumkin.

In [ ]:
df2.rename(index={'Macau':'MAKAO'}, columns={'pop2021':'population'})

                  rank     density   densityMi  population     area
country
MAKAO                1  21946.4667  56841.3487     658.394       30
Monaco               2  19755.5000  51166.7450      39.511        2
Burundi             28    440.3044   1140.3884   12255.433    27834
MAKAO                1  21946.4667  56841.3487     658.394       30
Monaco               2  19755.5000  51166.7450      39.511        2
...                ...         ...         ...         ...      ...
Namibia            228      3.1338      8.1166    2587.344   825615
Western Sahara     229      2.3003      5.9577     611.875   266000
Mongolia           230      2.1286      5.5129    3329.289  1564110
Falkland Islands   231      0.2902      0.7517       3.533    12173
Greenland          232      0.0263      0.0680      56.877  2166086

[247 rows x 5 columns]

In [ ]:
df2.rename(columns=str.upper)

                  RANK     DENSITY   DENSITYMI    POP2021     AREA
country
Macau                1  21946.4667  56841.3487    658.394       30
Monaco               2  19755.5000  51166.7450     39.511        2
Burundi             28    440.3044   1140.3884  12255.433    27834
Macau                1  21946.4667  56841.3487    658.394       30
Monaco               2  19755.5000  51166.7450     39.511        2
...                ...         ...         ...        ...      ...
Namibia            228      3.1338      8.1166   2587.344   825615
Western Sahara     229      2.3003      5.9577    611.875   266000
Mongolia           230      2.1286      5.5129   3329.289  1564110
Falkland Islands   231      0.2902      0.7517      3.533    12173
Greenland          232      0.0263      0.0680     56.877  2166086

[247 rows x 5 columns]