![Imgur](https://i.imgur.com/h4PPC71.png)
#11-modul. Maʼlumotlarga ishlov berish. Maʼlumotlarni tayyorlash
# 11.28. Modul boʻyicha yakuniy amaliy vazifa

**Bu vazifalarni bajargach, maʼlumotlarni yuklash, tozalash, oʻzgartirish, matnlarni normalizatsiya qilish, qiymatlarni tekshirish, guruhlash va tahlil qilish kabi maʼlumotlarga ishlov berish (data processing) koʻnikmalarini egallaysiz.**

#**Umumiy maʼlumotlar bilan ishlash**

#Dataset haqida qisqacha maʼlumot
Restoran savdosi boʻyicha maʼlumotlar toʻplami 17 534 tranzaksiya uchun maʼlumotlarni oʻz ichiga oladi. Maʼlumotlar yetishmayotgan yoki baʼzilari toʻliq kiritilmagan boʻlishi mumkin. Maʼlumotlar toʻplamida asosiy taomlar, shirinliklar, ichimliklar kabi bir nechta toifadagi savdo tafsilotlari mavjud.


 0.   **Unnamed 0** – indekslarni;
 1.   **Order ID** – buyurtma IDʼsini;
 2.   **Customer ID** – mijoz IDʼsini;
 3.   **Category** – mahsulotlar kategoriyasini;
 4.   **Item** – mahsulot nomini;
 5.   **Price** – mahsulotning narxini;
 6.   **Quantity** – qancha mahsulot sotilgani miqdorini;
 7.   **Order Total** – umumiy narx qancha ekanini;
 8.   **Order Date** – buyurtma berilgan sanani (vaqt);
 9.   **Payment Method** – toʻlov usuli turini saqlaydi.

#1) Quyida berilgan datasetni yuklab olib, ustun nomlarini koʻring va ularni maʼno jihatdan tushunarli shaklga keltiring. `Unnamed: 0` ustunini tashlab yuboring!

In [1]:
import pandas as pd
import numpy as np

url = "https://raw.githubusercontent.com/alishermutalov/praktikum-datasets/refs/heads/praktikum/restaurant_sales.csv"
df = pd.read_csv(url)
df.head()

,Unnamed: 0,Order ID,Customer ID,Category,Item,Price,Quantity,Order Total,Order Date,Payment Method
0,0,ORD_705844,CUST_092,NaN,side salad#?,3.0,1.0,3.0,2023-12-21,Credit Card
1,1,ORD_338528,CUST_021,Side Dishes,Mashed Potatoes,4.0,3.0,12.0,2023-05-19,Digital Wallet
2,2,ORD_443849,CUST_029,Main Dishes,Grilled Chicken,15.0,4.0,60.0,2023-09-27,Credit Card
3,3,ORD_630508,CUST_075,Drinks,NaN,-1.0,2.0,5.0,2022-08-09,Credit Card
4,4,ORD_648269,CUST_031,Main Dishes,Pasta Alfredo,12.0,4.0,48.0,2022-05-15,Cash

In [2]:
df.drop(columns=['Unnamed: 0'], inplace=True)
df.columns = [col.lower().replace(' ', '_') for col in df.columns]

print("Yangi ustun nomlari:", df.columns.tolist())
df.head()

Yangi ustun nomlari: ['order_id', 'customer_id', 'category', 'item', 'price', 'quantity', 'order_total', 'order_date', 'payment_method']

,order_id,customer_id,category,item,price,quantity,order_total,order_date,payment_method
0,ORD_705844,CUST_092,NaN,side salad#?,3.0,1.0,3.0,2023-12-21,Credit Card
1,ORD_338528,CUST_021,Side Dishes,Mashed Potatoes,4.0,3.0,12.0,2023-05-19,Digital Wallet
2,ORD_443849,CUST_029,Main Dishes,Grilled Chicken,15.0,4.0,60.0,2023-09-27,Credit Card
3,ORD_630508,CUST_075,Drinks,NaN,-1.0,2.0,5.0,2022-08-09,Credit Card
4,ORD_648269,CUST_031,Main Dishes,Pasta Alfredo,12.0,4.0,48.0,2022-05-15,Cash

#2) Maʼlumotlarning umumiy holatini (info(), describe()) tekshiring.

In [3]:
# 1. Ma'lumotlarning umumiy tarkibi va turlari haqida ma'lumot
print("--- Dataset haqida umumiy ma'lumot (info) ---")
df.info()

# 2. Raqamli ustunlar uchun statistik tahlil
print("\n--- Statistik ko'rsatkichlar (describe) ---")
# include='all' parametri yordamida ham raqamli, ham matnli ustunlarni ko'rish mumkin
df_stats = df.describe(include='all')
df_stats

--- Dataset haqida umumiy ma'lumot (info) ---
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 17534 entries, 0 to 17533
Data columns (total 9 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   order_id        17534 non-null  object
 1   customer_id     17534 non-null  object
 2   category        17498 non-null  object
 3   item            15776 non-null  object
 4   price           17534 non-null  float64
 5   quantity        17104 non-null  float64
 6   order_total     17104 non-null  float64
 7   order_date      17534 non-null  object
 8   payment_method  16452 non-null  object
dtypes: float64(3), object(6)
memory usage: 1.2+ MB

--- Statistik ko'rsatkichlar (describe) ---

,order_id,customer_id,category,item,price,quantity,order_total,order_date,payment_method
count,17534,17534,17498,15776,17534.000000,17104.000000,17104.000000,17534,16452
unique,17534,100,5,176,NaN,NaN,NaN,730,3
top,ORD_680707,CUST_066,Main Dishes,Pasta Alfredo,NaN,NaN,NaN,2023-11-25,Credit Card
freq,1,207,3544,927,NaN,NaN,NaN,42,5504
mean,NaN,NaN,NaN,NaN,6.207312,3.014149,19.914494,NaN,NaN
std,NaN,NaN,NaN,NaN,4.993782,1.414598,18.732549,NaN,NaN
min,NaN,NaN,NaN,NaN,-1.000000,1.000000,1.000000,NaN,NaN
25%,NaN,NaN,NaN,NaN,3.000000,2.000000,7.500000,NaN,NaN
50%,NaN,NaN,NaN,NaN,5.000000,3.000000,15.000000,NaN,NaN
75%,NaN,NaN,NaN,NaN,7.000000,4.000000,25.000000,NaN,NaN
max,NaN,NaN,NaN,NaN,20.000000,5.000000,100.000000,NaN,NaN

#3) Har bir ustundagi boʻsh qiymatlarni aniqlang va ularni toʻldirish strategiyasini ishlab chiqing.

In [4]:
categorical_cols = ['category', 'item', 'payment_method']
for col in categorical_cols:
    df[col] = df[col].fillna("Unknown")

df['price'] = df['price'].fillna(df['price'].median())
df['quantity'] = df['quantity'].fillna(df['quantity'].median())

df['order_total'] = df['order_total'].fillna(df['price'] * df['quantity'])

df.dropna(subset=['order_date'], inplace=True)

print("Tozalashdan keyingi bo'sh qiymatlar:")
print(df.isnull().sum())

Tozalashdan keyingi bo'sh qiymatlar:
order_id          0
customer_id       0
category          0
item              0
price             0
quantity          0
order_total       0
order_date        0
payment_method    0
dtype: int64

#4) Har bir ustundagi takroriy qiymatlarni toping va ularga qanday oʻzgartirish kiritish kerakligini hal qiling.

In [5]:
df.drop(columns=['Unnamed: 0'], inplace=True, errors='ignore')
df.columns = [col.lower().replace(' ', '_') for col in df.columns]

text_cols = ['category', 'item', 'payment_method']
for col in text_cols:
    df[col] = df[col].astype(str).str.strip().str.lower()

df['category'] = df['category'].replace('nan', 'unknown')
df['item'] = df['item'].replace('nan', 'unknown')
df['price'] = df['price'].fillna(df['price'].median())
df['quantity'] = df['quantity'].fillna(df['quantity'].median())

df['order_total'] = df['order_total'].fillna(df['price'] * df['quantity'])

df.drop_duplicates(inplace=True)

df['order_date'] = pd.to_datetime(df['order_date'])

print("Dataset hajmi:", df.shape)
print("\nBo'sh qiymatlar soni:\n", df.isnull().sum())
df.head()

Dataset hajmi: (17534, 9)

Bo'sh qiymatlar soni:
 order_id          0
customer_id       0
category          0
item              0
price             0
quantity          0
order_total       0
order_date        0
payment_method    0
dtype: int64

,order_id,customer_id,category,item,price,quantity,order_total,order_date,payment_method
0,ORD_705844,CUST_092,unknown,side salad#?,3.0,1.0,3.0,2023-12-21,credit card
1,ORD_338528,CUST_021,side dishes,mashed potatoes,4.0,3.0,12.0,2023-05-19,digital wallet
2,ORD_443849,CUST_029,main dishes,grilled chicken,15.0,4.0,60.0,2023-09-27,credit card
3,ORD_630508,CUST_075,drinks,unknown,-1.0,2.0,5.0,2022-08-09,credit card
4,ORD_648269,CUST_031,main dishes,pasta alfredo,12.0,4.0,48.0,2022-05-15,cash

#5) Maʼlumotlar toʻplamidagi noto‘g‘ri maʼlumotlar (masalan, son turishi kerak bo‘lgan ustunda matn bo‘lsa) mavjudligini tekshiring va to‘g‘rilang.

In [6]:
numeric_cols = ['price', 'quantity', 'order_total']

for col in numeric_cols:
    df[col] = pd.to_numeric(df[col], errors='coerce')

df['price'] = df['price'].fillna(df['price'].median())
df['quantity'] = df['quantity'].fillna(df['quantity'].median())
df['order_total'] = df['price'] * df['quantity']
print("Ustunlarning yakuniy turlari:")
print(df[numeric_cols].dtypes)

df.head()

Ustunlarning yakuniy turlari:
price          float64
quantity       float64
order_total    float64
dtype: object

,order_id,customer_id,category,item,price,quantity,order_total,order_date,payment_method
0,ORD_705844,CUST_092,unknown,side salad#?,3.0,1.0,3.0,2023-12-21,credit card
1,ORD_338528,CUST_021,side dishes,mashed potatoes,4.0,3.0,12.0,2023-05-19,digital wallet
2,ORD_443849,CUST_029,main dishes,grilled chicken,15.0,4.0,60.0,2023-09-27,credit card
3,ORD_630508,CUST_075,drinks,unknown,-1.0,2.0,-2.0,2022-08-09,credit card
4,ORD_648269,CUST_031,main dishes,pasta alfredo,12.0,4.0,48.0,2022-05-15,cash

#6) Maʼlumotlar toʻplamidagi **katta/kichik harf** muammolari boʻlgan joylarni toping va bir xil formatga keltiring.

In [7]:
text_columns = ['category', 'item', 'payment_method']

for col in text_columns:

    df[col] = df[col].astype(str).str.strip().str.lower()

print("Kategoriyalar:", df['category'].unique())
print("To'lov usullari:", df['payment_method'].unique())

df.drop_duplicates(inplace=True)

df.head()

Kategoriyalar: ['unknown' 'side dishes' 'main dishes' 'drinks' 'desserts' 'starters']
To'lov usullari: ['credit card' 'digital wallet' 'cash' 'unknown']

,order_id,customer_id,category,item,price,quantity,order_total,order_date,payment_method
0,ORD_705844,CUST_092,unknown,side salad#?,3.0,1.0,3.0,2023-12-21,credit card
1,ORD_338528,CUST_021,side dishes,mashed potatoes,4.0,3.0,12.0,2023-05-19,digital wallet
2,ORD_443849,CUST_029,main dishes,grilled chicken,15.0,4.0,60.0,2023-09-27,credit card
3,ORD_630508,CUST_075,drinks,unknown,-1.0,2.0,-2.0,2022-08-09,credit card
4,ORD_648269,CUST_031,main dishes,pasta alfredo,12.0,4.0,48.0,2022-05-15,cash

#7) Maʼlumotlar turini oʻzgartirish.
 * Ustunlarning maʼlumot turlarini tekshiring. Notoʻgʻri turlarga ega boʻlgan ustunlarni toʻgʻri formatga oʻtkazing.
 * `order_date` yoki unga oʻxshash ustunni datetime formatiga oʻtkazing.

In [8]:
print("O'zgartirishdan oldingi turlar:\n", df.dtypes)

df['order_date'] = pd.to_datetime(df['order_date'])

df['quantity'] = df['quantity'].astype(int)
df['price'] = df['price'].astype(float)
df['order_total'] = df['order_total'].astype(float)
df['category'] = df['category'].astype('category')
df['payment_method'] = df['payment_method'].astype('category')

print("\nO'zgartirishdan keyingi turlar:\n", df.dtypes)
df.head()

O'zgartirishdan oldingi turlar:
 order_id                  object
customer_id               object
category                  object
item                      object
price                    float64
quantity                 float64
order_total              float64
order_date        datetime64[ns]
payment_method            object
dtype: object

O'zgartirishdan keyingi turlar:
 order_id                  object
customer_id               object
category                category
item                      object
price                    float64
quantity                   int64
order_total              float64
order_date        datetime64[ns]
payment_method          category
dtype: object

,order_id,customer_id,category,item,price,quantity,order_total,order_date,payment_method
0,ORD_705844,CUST_092,unknown,side salad#?,3.0,1,3.0,2023-12-21,credit card
1,ORD_338528,CUST_021,side dishes,mashed potatoes,4.0,3,12.0,2023-05-19,digital wallet
2,ORD_443849,CUST_029,main dishes,grilled chicken,15.0,4,60.0,2023-09-27,credit card
3,ORD_630508,CUST_075,drinks,unknown,-1.0,2,-2.0,2022-08-09,credit card
4,ORD_648269,CUST_031,main dishes,pasta alfredo,12.0,4,48.0,2022-05-15,cash

#8) Mahsulot nomlarida noto‘g‘ri yoki nomaʼlum belgilar (?, NaN, #) mavjudligini tekshiring va ularni tuzating.

In [9]:
import re

def clean_text(text):
    if pd.isna(text) or str(text).lower() == 'nan':
        return "unknown"
    text = re.sub(r'[^a-zA-Z0-9\s]', '', str(text))

    text = " ".join(text.split())

    return text.lower()

df['item'] = df['item'].apply(clean_text)
df['category'] = df['category'].apply(clean_text)
print("Tozalashdan keyingi 'unknown' qiymatlar soni:")
print(df[df['item'] == 'unknown']['item'].count())

df.head(10)

Tozalashdan keyingi 'unknown' qiymatlar soni:
1758

,order_id,customer_id,category,item,price,quantity,order_total,order_date,payment_method
0,ORD_705844,CUST_092,unknown,side salad,3.0,1,3.0,2023-12-21,credit card
1,ORD_338528,CUST_021,side dishes,mashed potatoes,4.0,3,12.0,2023-05-19,digital wallet
2,ORD_443849,CUST_029,main dishes,grilled chicken,15.0,4,60.0,2023-09-27,credit card
3,ORD_630508,CUST_075,drinks,unknown,-1.0,2,-2.0,2022-08-09,credit card
4,ORD_648269,CUST_031,main dishes,pasta alfredo,12.0,4,48.0,2022-05-15,cash
5,ORD_381680,CUST_031,main dishes,salmon,18.0,5,90.0,2022-07-20,digital wallet
6,ORD_270994,CUST_071,side dishes,garlic bread,4.0,5,20.0,2022-08-19,credit card
7,ORD_146656,CUST_077,main dishes,unknown,15.0,3,45.0,2023-02-15,cash
8,ORD_428611,CUST_083,desserts,unknown,6.0,2,12.0,2023-12-16,cash
9,ORD_743636,CUST_085,main dishes,vegetarian platter,14.0,5,70.0,2022-08-07,unknown

#**Maʼlumotlarni filtrlash va qayta ishlash**

#9) Manfiy narx yoki 0 ga teng narx qiymatlarini toping va ularni qanday oʻzgartirish kerakligini hal qiling.

In [10]:
df.drop(columns=['Unnamed: 0'], inplace=True, errors='ignore')
df.columns = [col.lower().replace(' ', '_') for col in df.columns]
def clean_text(text):
    if pd.isna(text) or str(text).lower() == 'nan':
        return "unknown"
    text = re.sub(r'[^a-zA-Z0-9\s]', '', str(text))
    return " ".join(text.split()).lower()

text_cols = ['category', 'item', 'payment_method']
for col in text_cols:
    df[col] = df[col].apply(clean_text)
numeric_cols = ['price', 'quantity', 'order_total']
for col in numeric_cols:
    df[col] = pd.to_numeric(df[col], errors='coerce')
df.loc[df['price'] <= 0, 'price'] = np.nan
df['price'] = df['price'].fillna(df.groupby('category')['price'].transform('median'))
df['price'] = df['price'].fillna(df['price'].median())

df['quantity'] = df['quantity'].fillna(df['quantity'].median())

df['order_total'] = df['price'] * df['quantity']

df['order_date'] = pd.to_datetime(df['order_date'])
df['quantity'] = df['quantity'].astype(int)
df['price'] = df['price'].astype(float)
df['category'] = df['category'].astype('category')

df.drop_duplicates(inplace=True)

print("--- Dataset haqida umumiy ma'lumot ---")
df.info()

print("\n--- Bo'sh qiymatlar soni ---")
print(df.isnull().sum())

print("\n--- Statistik ko'rsatkichlar ---")
print(df.describe())

df.head()

--- Dataset haqida umumiy ma'lumot ---
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 17534 entries, 0 to 17533
Data columns (total 9 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   order_id        17534 non-null  object
 1   customer_id     17534 non-null  object
 2   category        17534 non-null  category
 3   item            17534 non-null  object
 4   price           17534 non-null  float64
 5   quantity        17534 non-null  int64
 6   order_total     17534 non-null  float64
 7   order_date      17534 non-null  datetime64[ns]
 8   payment_method  17534 non-null  category
dtypes: category(2), datetime64[ns](1), float64(2), int64(1), object(3)
memory usage: 993.7+ KB

--- Bo'sh qiymatlar soni ---
order_id          0
customer_id       0
category          0
item              0
price             0
quantity          0
order_total       0
order_date        0
payment_method    0
dtype: int64

--- Statistik ko'rsatkichlar ---
              price      quantity   order_total                     order_date
count  17534.000000  17534.000000  17534.000000                          17534
mean       6.584835      3.013802     19.897742  2022-12-28 15:19:09.355538176
min        1.000000      1.000000      1.000000            2022-01-01 00:00:00
25%        3.000000      2.000000      7.500000            2022-06-30 00:00:00
50%        5.000000      3.000000     15.000000            2022-12-25 00:00:00
75%        7.000000      4.000000     25.000000            2023-06-29 00:00:00
max       20.000000      5.000000    100.000000            2023-12-31 00:00:00
std        4.816247      1.397145     18.565542                            NaN

/tmp/ipykernel_4774/800822599.py:16: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  df['price'] = df['price'].fillna(df.groupby('category')['price'].transform('median'))

,order_id,customer_id,category,item,price,quantity,order_total,order_date,payment_method
0,ORD_705844,CUST_092,unknown,side salad,3.0,1,3.0,2023-12-21,credit card
1,ORD_338528,CUST_021,side dishes,mashed potatoes,4.0,3,12.0,2023-05-19,digital wallet
2,ORD_443849,CUST_029,main dishes,grilled chicken,15.0,4,60.0,2023-09-27,credit card
3,ORD_630508,CUST_075,drinks,unknown,2.5,2,5.0,2022-08-09,credit card
4,ORD_648269,CUST_031,main dishes,pasta alfredo,12.0,4,48.0,2022-05-15,cash

#10) Boʻsh toifalar (kategoriya) mavjudligini tekshiring va toʻgʻri kategoriya berish strategiyasini ishlab chiqing.

In [11]:
df['category'] = df['category'].replace(['unknown', 'nan', 'none', ''], np.nan)
df['category'] = df['category'].fillna(df.groupby('item')['category'].transform('first'))
def fill_by_keyword(row):
    if pd.isna(row['category']):
        item = str(row['item']).lower()
        if any(x in item for x in ['tea', 'coffee', 'juice', 'cola', 'water']):
            return 'beverages'
        elif any(x in item for x in ['cake', 'ice cream', 'pudding']):
            return 'desserts'
        elif any(x in item for x in ['pizza', 'burger', 'steak', 'pasta']):
            return 'main course'
    return row['category']

df['category'] = df.apply(fill_by_keyword, axis=1)
df['category'] = df['category'].fillna('others')

print("Bo'sh kategoriyalar qoldimi:", df['category'].isnull().sum())
print("\nYangilangan kategoriyalar ro'yxati:\n", df['category'].value_counts())

/tmp/ipykernel_4774/3319699712.py:1: FutureWarning: The behavior of Series.replace (and DataFrame.replace) with CategoricalDtype is deprecated. In a future version, replace will only be used for cases that preserve the categories. To change the categories, use ser.cat.rename_categories instead.
  df['category'] = df['category'].replace(['unknown', 'nan', 'none', ''], np.nan)

Bo'sh kategoriyalar qoldimi: 0

Yangilangan kategoriyalar ro'yxati:
 category
main dishes    3550
starters       3525
desserts       3496
drinks         3492
side dishes    3471
Name: count, dtype: int64

#11) Bir xil, lekin turlicha yozilgan qiymatlar (Coffee, cofee, COFEE) mavjudligini tekshiring va tuzating.

In [12]:
df.drop(columns=['Unnamed: 0'], inplace=True, errors='ignore')
df.columns = [col.lower().replace(' ', '_') for col in df.columns]

def clean_text(text):
    if pd.isna(text) or str(text).lower() == 'nan':
        return "unknown"
    text = re.sub(r'[^a-zA-Z0-9\s]', '', str(text))
    text = " ".join(text.split()).lower()
    return text

text_cols = ['category', 'item', 'payment_method']
for col in text_cols:
    df[col] = df[col].apply(clean_text)
corrections = {
    'cofee': 'coffee', 'cofeee': 'coffee', 'burgerr': 'burger',
    'piza': 'pizza', 'steyk': 'steak', 'teaa': 'tea'
}
df['item'] = df['item'].replace(corrections)
numeric_cols = ['price', 'quantity', 'order_total']
for col in numeric_cols:
    df[col] = pd.to_numeric(df[col], errors='coerce')

df.loc[df['price'] <= 0, 'price'] = np.nan
df['price'] = df['price'].fillna(df.groupby('category')['price'].transform('median'))
df['price'] = df['price'].fillna(df['price'].median())
df['quantity'] = df['quantity'].fillna(df['quantity'].median())

item_cat_map = df.dropna(subset=['category']).set_index('item')['category'].to_dict()
df['category'] = df['category'].replace('unknown', np.nan)
df['category'] = df['category'].fillna(df['item'].map(item_cat_map))
df['category'] = df['category'].fillna('others')

df['order_total'] = df['price'] * df['quantity']

df['order_date'] = pd.to_datetime(df['order_date'])
df['quantity'] = df['quantity'].astype(int)
df['category'] = df['category'].astype('category')

df.drop_duplicates(inplace=True)

print("--- Dataset haqida ma'lumot ---")
df.info()
print("\n--- Statistik ko'rsatkichlar ---")
print(df.describe())
print("\n--- Bo'sh qiymatlar ---")
print(df.isnull().sum())

df.head()

--- Dataset haqida ma'lumot ---
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 17534 entries, 0 to 17533
Data columns (total 9 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   order_id        17534 non-null  object
 1   customer_id     17534 non-null  object
 2   category        17534 non-null  category
 3   item            17534 non-null  object
 4   price           17534 non-null  float64
 5   quantity        17534 non-null  int64
 6   order_total     17534 non-null  float64
 7   order_date      17534 non-null  datetime64[ns]
 8   payment_method  17534 non-null  category
dtypes: category(2), datetime64[ns](1), float64(2), int64(1), object(3)
memory usage: 993.7+ KB

--- Statistik ko'rsatkichlar ---
              price      quantity   order_total                     order_date
count  17534.000000  17534.000000  17534.000000                          17534
mean       6.584835      3.013802     19.897742  2022-12-28 15:19:09.355538176
min        1.000000      1.000000      1.000000            2022-01-01 00:00:00
25%        3.000000      2.000000      7.500000            2022-06-30 00:00:00
50%        5.000000      3.000000     15.000000            2022-12-25 00:00:00
75%        7.000000      4.000000     25.000000            2023-06-29 00:00:00
max       20.000000      5.000000    100.000000            2023-12-31 00:00:00
std        4.816247      1.397145     18.565542                            NaN

--- Bo'sh qiymatlar ---
order_id          0
customer_id       0
category          0
item              0
price             0
quantity          0
order_total       0
order_date        0
payment_method    0
dtype: int64

,order_id,customer_id,category,item,price,quantity,order_total,order_date,payment_method
0,ORD_705844,CUST_092,side dishes,side salad,3.0,1,3.0,2023-12-21,credit card
1,ORD_338528,CUST_021,side dishes,mashed potatoes,4.0,3,12.0,2023-05-19,digital wallet
2,ORD_443849,CUST_029,main dishes,grilled chicken,15.0,4,60.0,2023-09-27,credit card
3,ORD_630508,CUST_075,drinks,unknown,2.5,2,5.0,2022-08-09,credit card
4,ORD_648269,CUST_031,main dishes,pasta alfredo,12.0,4,48.0,2022-05-15,cash

#12) `Customer ID` yoki boshqa identifikatorlarning takrorlanishini tekshiring.

In [13]:
customer_revisits = df['customer_id'].value_counts()
loyal_customers = customer_revisits[customer_revisits > 1]

print(f"Jami noyob mijozlar soni: {df['customer_id'].nunique()}")
print(f"Qayta tashrif buyurgan (sodiq) mijozlar soni: {len(loyal_customers)}")
order_items_count = df['order_id'].value_counts()
print(f"Bitta buyurtmada eng ko'p mahsulot sotib olingan soni: {order_items_count.max()}")

duplicate_mask = df.duplicated(subset=['order_id', 'customer_id', 'item', 'order_date'], keep='first')
duplicate_count = duplicate_mask.sum()

if duplicate_count > 0:
    print(f"\nAniqlangan texnik xato dublikatlar soni: {duplicate_count}")
    df = df.drop_duplicates(subset=['order_id', 'customer_id', 'item', 'order_date'], keep='first')
    print("Texnik dublikatlar muvaffaqiyatli o'chirildi.")
else:
    print("\nTexnik xato dublikatlar aniqlanmadi.")
print(f"\nIDsi yo'q mijozlar soni: {df['customer_id'].isnull().sum()}")
print(f"IDsi yo'q buyurtmalar soni: {df['order_id'].isnull().sum()}")
print("\nEng ko'p daromad keltirgan 5 ta mijoz (Top Customers):")
top_customers = df.groupby('customer_id')['order_total'].sum().sort_values(ascending=False)
print(top_customers.head())

Jami noyob mijozlar soni: 100
Qayta tashrif buyurgan (sodiq) mijozlar soni: 100
Bitta buyurtmada eng ko'p mahsulot sotib olingan soni: 1

Texnik xato dublikatlar aniqlanmadi.

IDsi yo'q mijozlar soni: 0
IDsi yo'q buyurtmalar soni: 0

Eng ko'p daromad keltirgan 5 ta mijoz (Top Customers):
customer_id
CUST_028    4217.0
CUST_020    4202.5
CUST_089    4163.5
CUST_019    4138.0
CUST_017    4101.5
Name: order_total, dtype: float64

#13) Mahsulotning ortiqcha taʼriflarini olib tashlang (Water (0.5), Water (1.0), Water → faqat Water qoldirish).

In [14]:
def clean_item_description(item_name):
    if pd.isna(item_name):
        return "unknown"
    cleaned = re.sub(r'\(.*?\)', '', str(item_name))

    cleaned = cleaned.split('—')[0].split('-')[0]
    return cleaned.strip().lower()
df['item'] = df['item'].apply(clean_item_description)

print("Tozalashdan keyingi noyob mahsulotlar (masalan, barcha Water'lar birlashdi):")
print(df['item'].unique()[:15])
print(f"\nBirlashishdan keyingi umumiy qatorlar soni: {len(df)}")

Tozalashdan keyingi noyob mahsulotlar (masalan, barcha Water'lar birlashdi):
['side salad' 'mashed potatoes' 'grilled chicken' 'unknown'
 'pasta alfredo' 'salmon' 'garlic bread' 'vegetarian platter' 'brownie'
 'sweet potato fries' 'lemonade' 'orange juice' 'chocolate cake'
 'coca cola' 'grilled vegetables']

Birlashishdan keyingi umumiy qatorlar soni: 17534

#**Qayta ishlangan maʼlumotlar bilan tahlil**

#14) Eng koʻp sotilgan 5 ta mahsulotni aniqlang.

In [15]:
top_5_items = df.groupby('item')['quantity'].sum().sort_values(ascending=False).head(5)
print("--- Eng ko'p sotilgan 5 ta mahsulot ---")
print(top_5_items)

top_5_revenue = df.groupby('item')['order_total'].sum().loc[top_5_items.index]
print("\n--- Ushbu mahsulotlardan tushgan umumiy tushum ---")
print(top_5_revenue)

--- Eng ko'p sotilgan 5 ta mahsulot ---
item
unknown          5270
pasta alfredo    3094
side salad       2932
ice cream        2929
water 05         2726
Name: quantity, dtype: int64

--- Ushbu mahsulotlardan tushgan umumiy tushum ---
item
unknown          34205.5
pasta alfredo    37128.0
side salad        8796.0
ice cream        14645.0
water 05          2726.0
Name: order_total, dtype: float64

#15) Har bir mijoz oʻrtacha qancha pul sarflaganini hisoblang.

In [16]:
customer_spending = df.groupby('customer_id')['order_total'].sum()
average_spending_per_customer = customer_spending.mean()

print(f"Bitta mijoz o'rtacha sarflagan summa: {average_spending_per_customer:.2f}")

print("\n--- Eng ko'p pul sarflagan Top-5 mijoz ---")
print(customer_spending.sort_values(ascending=False).head(5))

Bitta mijoz o'rtacha sarflagan summa: 3488.87

--- Eng ko'p pul sarflagan Top-5 mijoz ---
customer_id
CUST_028    4217.0
CUST_020    4202.5
CUST_089    4163.5
CUST_019    4138.0
CUST_017    4101.5
Name: order_total, dtype: float64

#16) Mijozlarning qaysi kunlarda koʻproq xarid qilgani bo‘yicha tahlil qiling.

In [17]:
df['day_of_week'] = df['order_date'].dt.day_name()

weekly_sales = df['day_of_week'].value_counts()
days_order = ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday']
weekly_sales = weekly_sales.reindex(days_order)

print("--- Haftaning kunlari bo'yicha buyurtmalar soni ---")
print(weekly_sales)

weekly_revenue = df.groupby('day_of_week')['order_total'].sum().reindex(days_order)
print("\n--- Haftaning kunlari bo'yicha umumiy tushum ---")
print(weekly_revenue)

--- Haftaning kunlari bo'yicha buyurtmalar soni ---
day_of_week
Monday       2526
Tuesday      2477
Wednesday    2477
Thursday     2515
Friday       2531
Saturday     2525
Sunday       2483
Name: count, dtype: int64

--- Haftaning kunlari bo'yicha umumiy tushum ---
day_of_week
Monday       50465.5
Tuesday      50734.0
Wednesday    48047.5
Thursday     49245.5
Friday       49745.0
Saturday     49779.5
Sunday       50870.0
Name: order_total, dtype: float64

#17) Narxi oʻrtacha narxdan ikki barobar yuqori boʻlgan mahsulotlarni toping.

In [18]:
average_price = df['price'].mean()
print(f"Barcha mahsulotlarning o'rtacha narxi: {average_price:.2f}")
threshold = average_price * 2
print(f"2 barobar yuqori bo'lgan chegara (Threshold): {threshold:.2f}")

expensive_items = df[df['price'] > threshold][['item', 'category', 'price']].drop_duplicates()

print("\n--- O'rtacha narxdan 2 barobar qimmat mahsulotlar ---")
print(expensive_items.sort_values(by='price', ascending=False))

Barcha mahsulotlarning o'rtacha narxi: 6.58
2 barobar yuqori bo'lgan chegara (Threshold): 13.17

--- O'rtacha narxdan 2 barobar qimmat mahsulotlar ---
                   item     category  price
731             unknown  main dishes   20.0
125               steak  main dishes   20.0
5                salmon  main dishes   18.0
35              unknown  main dishes   18.0
2       grilled chicken  main dishes   15.0
7               unknown  main dishes   15.0
9    vegetarian platter  main dishes   14.0
796             unknown  main dishes   14.0

#18) Mahsulotlar kategoriyalari bo‘yicha tahlil qiling va eng ko‘p sotiladigan kategoriyalarni aniqlang.

In [19]:
category_analysis = df.groupby('category').agg({
    'quantity': 'sum',
    'order_total': 'sum'
}).sort_values(by='quantity', ascending=False)

total_quantity = category_analysis['quantity'].sum()
category_analysis['market_share_%'] = (category_analysis['quantity'] / total_quantity) * 100

print("--- Kategoriyalar bo'yicha sotuv tahlili ---")
print(category_analysis)

top_category = category_analysis.index[0]
print(f"\nEng ommabop kategoriya: {top_category.upper()}")

--- Kategoriyalar bo'yicha sotuv tahlili ---
             quantity  order_total  market_share_%
category
main dishes     10816     164342.0       20.467792
starters        10591      61017.0       20.042010
drinks          10532      23442.0       19.930361
desserts        10522      58659.0       19.911437
side dishes     10383      41427.0       19.648399

Eng ommabop kategoriya: MAIN DISHES

/tmp/ipykernel_4774/3869232594.py:1: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  category_analysis = df.groupby('category').agg({

#19) Har bir mijozning oʻrtacha xarid miqdorini (`groupby("customer_id")`) hisoblang.

In [20]:
customer_avg_stats = df.groupby('customer_id').agg({
    'order_total': 'mean',
    'quantity': 'mean'
}).rename(columns={
    'order_total': 'avg_spent',
    'quantity': 'avg_quantity'
})
print("--- Har bir mijozning o'rtacha xarid ko'rsatkichlari (Top 10) ---")
print(customer_avg_stats.sort_values(by='avg_spent', ascending=False).head(10))

overall_avg_quantity = customer_avg_stats['avg_quantity'].mean()
print(f"\nRestoran bo'yicha bitta mijozning o'rtacha xarid miqdori: {overall_avg_quantity:.2f} ta mahsulot")

--- Har bir mijozning o'rtacha xarid ko'rsatkichlari (Top 10) ---
             avg_spent  avg_quantity
customer_id
CUST_046     22.941558      3.246753
CUST_017     22.660221      3.209945
CUST_089     22.627717      3.125000
CUST_020     22.473262      2.935829
CUST_080     22.120588      2.935294
CUST_086     22.091667      3.016667
CUST_023     22.064626      3.190476
CUST_006     21.917722      3.050633
CUST_054     21.870968      2.973118
CUST_093     21.824324      3.135135

Restoran bo'yicha bitta mijozning o'rtacha xarid miqdori: 3.01 ta mahsulot

#20) Qanday omillar sotuv hajmiga ta’sir qiladi? Bu bo‘yicha umumiy xulosa chiqaring. Javobni quyida kommentariya sifatida yozing!

In [21]:
import pandas as pd
import numpy as np
import re

url = "https://raw.githubusercontent.com/alishermutalov/praktikum-datasets/refs/heads/praktikum/restaurant_sales.csv"
df = pd.read_csv(url)
df.drop(columns=['Unnamed: 0'], inplace=True, errors='ignore')
df.columns = df.columns.str.lower().str.replace(' ', '_')

def clean_item_name(text):
    if pd.isna(text): return "unknown"
    text = re.sub(r'\(.*?\)', '', str(text))
    text = re.sub(r'[^a-zA-Z0-9\s]', '', text)
    return " ".join(text.split()).lower()

for col in ['category', 'item', 'payment_method']:
    df[col] = df[col].apply(clean_text)

df['item'] = df['item'].replace({'cofee': 'coffee', 'piza': 'pizza', 'burgerr': 'burger'})

cols_to_fix = ['price', 'quantity', 'order_total']
df[cols_to_fix] = df[cols_to_fix].apply(pd.to_numeric, errors='coerce')

df.loc[df['price'] <= 0, 'price'] = np.nan
df['price'] = df['price'].fillna(df.groupby('category')['price'].transform('median'))
df['quantity'] = df['quantity'].fillna(df['quantity'].median())
df['order_total'] = df['price'] * df['quantity']
df['order_date'] = pd.to_datetime(df['order_date'])
df['category'] = df['category'].replace('unknown', np.nan)
df['category'] = df['category'].fillna(df.groupby('item')['category'].transform('first')).fillna('others')
df.drop_duplicates(inplace=True)
top_5 = df.groupby('item')['quantity'].sum().nlargest(5)
customer_avg = df.groupby('customer_id')['order_total'].mean().mean()
df['day'] = df['order_date'].dt.day_name()
top_day = df['day'].value_counts().idxmax()
premium_list = df[df['price'] > (df['price'].mean() * 2)]['item'].unique()
top_cat = df.groupby('category')['quantity'].sum().idxmax()
print(f"1. Top 5 mahsulot:\n{top_5}")
print(f"\n2. Mijozlarning o'rtacha xarajat summasi: {customer_avg:.2f}")
print(f"3. Savdo eng qizigan kun: {top_day}")
print(f"4. Eng ommabop kategoriya: {top_cat}")
print(f"5. Premium mahsulotlar soni: {len(premium_list)}")

1. Top 5 mahsulot:
item
unknown          5270.0
pasta alfredo    3094.0
side salad       2932.0
ice cream        2929.0
water 05         2726.0
Name: quantity, dtype: float64

2. Mijozlarning o'rtacha xarajat summasi: 19.90
3. Savdo eng qizigan kun: Friday
4. Eng ommabop kategoriya: main dishes
5. Premium mahsulotlar soni: 5